export { default as Activity } from '../..\\components\\Activity.vue'
export { default as Allowance } from '../..\\components\\Allowance.vue'
export { default as AreaChart } from '../..\\components\\AreaChart.vue'
export { default as Automation } from '../..\\components\\automation.vue'
export { default as Calender } from '../..\\components\\Calender.vue'
export { default as CalenderFullPage } from '../..\\components\\CalenderFullPage.vue'
export { default as Camera } from '../..\\components\\Camera.vue'
export { default as Cards } from '../..\\components\\Cards.vue'
export { default as ComboChart } from '../..\\components\\ComboChart.vue'
export { default as Commision } from '../..\\components\\Commision.vue'
export { default as ComonPreloader } from '../..\\components\\ComonPreloader.vue'
export { default as CSV } from '../..\\components\\CSV.vue'
export { default as CustomFilter } from '../..\\components\\CustomFilter.vue'
export { default as Deduction } from '../..\\components\\Deduction.vue'
export { default as DeviceAccessSettings } from '../..\\components\\DeviceAccessSettings.vue'
export { default as DeviceNotification } from '../..\\components\\DeviceNotification.vue'
export { default as Document } from '../..\\components\\Document.vue'
export { default as Donut } from '../..\\components\\Donut.vue'
export { default as Editor } from '../..\\components\\Editor.vue'
export { default as Employee } from '../..\\components\\Employee.vue'
export { default as EMPLOYEETOREPORT } from '../..\\components\\EMPLOYEETOREPORT.vue'
export { default as FacePreloader } from '../..\\components\\FacePreloader.vue'
export { default as ForgotPassword } from '../..\\components\\ForgotPassword.vue'
export { default as GenerateLog } from '../..\\components\\GenerateLog.vue'
export { default as Logs } from '../..\\components\\Logs.vue'
export { default as MultiInOutShiftEdit } from '../..\\components\\MultiInOutShiftEdit.vue'
export { default as NoAccess } from '../..\\components\\NoAccess.vue'
export { default as NoRecordFound } from '../..\\components\\NoRecordFound.vue'
export { default as OriginalLogs } from '../..\\components\\OriginalLogs.vue'
export { default as OverNightShiftEdit } from '../..\\components\\OverNightShiftEdit.vue'
export { default as Overtime } from '../..\\components\\Overtime.vue'
export { default as PIE } from '../..\\components\\PIE.vue'
export { default as PIE2 } from '../..\\components\\PIE2.vue'
export { default as PiePreloader } from '../..\\components\\PiePreloader.vue'
export { default as Preloader } from '../..\\components\\Preloader.vue'
export { default as RealTimeLogs } from '../..\\components\\RealTimeLogs.vue'
export { default as RenderAttendance } from '../..\\components\\RenderAttendance.vue'
export { default as SalaryToolbar } from '../..\\components\\SalaryToolbar.vue'
export { default as SingleShiftEdit } from '../..\\components\\SingleShiftEdit.vue'
export { default as Announcements } from '../..\\components\\announcements\\Announcements.vue'
export { default as AnnouncementsOld } from '../..\\components\\announcements\\Announcements_old.vue'
export { default as AnnouncementsAnnouncementType } from '../..\\components\\announcements\\AnnouncementType.vue'
export { default as AttendanceReport } from '../..\\components\\attendance_report\\report.vue'
export { default as AttendanceReportComponent } from '../..\\components\\attendance_report\\reportComponent.vue'
export { default as AttendanceReportComponentDual } from '../..\\components\\attendance_report\\reportComponent_dual.vue'
export { default as AttendanceReportComponentMulti } from '../..\\components\\attendance_report\\reportComponent_multi.vue'
export { default as BranchCreate } from '../..\\components\\branch\\BranchCreate.vue'
export { default as BranchDetails } from '../..\\components\\branch\\BranchDetails.vue'
export { default as ChartsPIE } from '../..\\components\\charts\\PIE.vue'
export { default as CommunityCreate } from '../..\\components\\Community\\Create.vue'
export { default as DashboardAnnouncment } from '../..\\components\\dashboard2\\DashboardAnnouncment.vue'
export { default as DashboardAnnouncmentV1 } from '../..\\components\\dashboard2\\DashboardAnnouncmentV1.vue'
export { default as DashboardAttednaceDepartmentWise } from '../..\\components\\dashboard2\\DashboardAttednaceDepartmentWise.vue'
export { default as DashboardAttednaceDepartmentWiseV1 } from '../..\\components\\dashboard2\\DashboardAttednaceDepartmentWiseV1.vue'
export { default as DashboardAttendanceChart } from '../..\\components\\dashboard2\\DashboardAttendanceChart.vue'
export { default as DashboardAttendanceChartV1 } from '../..\\components\\dashboard2\\DashboardAttendanceChartV1.vue'
export { default as DashboardAttendanceHourChart } from '../..\\components\\dashboard2\\DashboardAttendanceHourChart.vue'
export { default as DashboardAttendanceHourChartV1 } from '../..\\components\\dashboard2\\DashboardAttendanceHourChartV1.vue'
export { default as DashboardEmployeeAttendanceLog } from '../..\\components\\dashboard2\\DashboardEmployeeAttendanceLog.vue'
export { default as DashboardEmployeeAttendanceLogCopy } from '../..\\components\\dashboard2\\DashboardEmployeeAttendanceLog_copy.vue'
export { default as Dashboard2DashboardlastMultiStatistics } from '../..\\components\\dashboard2\\DashboardlastMultiStatistics.vue'
export { default as Dashboard2DashboardlLastMonthStatistics } from '../..\\components\\dashboard2\\DashboardlLastMonthStatistics.vue'
export { default as Dashboard2DashboardlLastMonthStatisticsV1 } from '../..\\components\\dashboard2\\DashboardlLastMonthStatisticsV1.vue'
export { default as DashboardLoginActivities } from '../..\\components\\dashboard2\\DashboardLoginActivities.vue'
export { default as DashboardLoginActivitiesV1 } from '../..\\components\\dashboard2\\DashboardLoginActivitiesV1.vue'
export { default as DashboardRealTimeLogTableview } from '../..\\components\\dashboard2\\DashboardRealTimeLogTableview.vue'
export { default as DashboardRealTimeLogTableviewV1 } from '../..\\components\\dashboard2\\DashboardRealTimeLogTableviewV1.vue'
export { default as DashboardRightsideStaticstics } from '../..\\components\\dashboard2\\DashboardRightsideStaticstics.vue'
export { default as DashboardRightsideStaticsticsV1 } from '../..\\components\\dashboard2\\DashboardRightsideStaticsticsV1.vue'
export { default as EmployeeBank } from '../..\\components\\employee\\Bank.vue'
export { default as EmployeeContact } from '../..\\components\\employee\\Contact.vue'
export { default as EmployeeCreateEmployee } from '../..\\components\\employee\\CreateEmployee.vue'
export { default as EmployeeDashboard } from '../..\\components\\employee\\Dashboard.vue'
export { default as EmployeeDocument } from '../..\\components\\employee\\Document.vue'
export { default as EmployeeEmirates } from '../..\\components\\employee\\Emirates.vue'
export { default as EmployeeDetails } from '../..\\components\\employee\\EmployeeDetails.vue'
export { default as EmployeeDetails2 } from '../..\\components\\employee\\EmployeeDetails2.vue'
export { default as EmployeeEmployeedevisesmap2 } from '../..\\components\\employee\\employeedevisesmap2.vue'
export { default as EmployeeEdit } from '../..\\components\\employee\\EmployeeEdit.vue'
export { default as EmployeeKeyValueTable } from '../..\\components\\employee\\KeyValueTable.vue'
export { default as EmployeeLogin } from '../..\\components\\employee\\Login.vue'
export { default as EmployeeLogs } from '../..\\components\\employee\\Logs.vue'
export { default as EmployeePassport } from '../..\\components\\employee\\Passport.vue'
export { default as EmployeePayroll } from '../..\\components\\employee\\Payroll.vue'
export { default as EmployeePersonal } from '../..\\components\\employee\\Personal.vue'
export { default as EmployeeQualification } from '../..\\components\\employee\\Qualification.vue'
export { default as EmployeeSetting } from '../..\\components\\employee\\Setting.vue'
export { default as EmployeeVisa } from '../..\\components\\employee\\Visa.vue'
export { default as EmployeeWorkInfo } from '../..\\components\\employee\\WorkInfo.vue'
export { default as EmployeesLoginEmployeeChangeRequest } from '../..\\components\\EmployeesLogin\\EmployeeChangeRequest.vue'
export { default as EmployeesLoginEmployeeLanding } from '../..\\components\\EmployeesLogin\\EmployeeLanding.vue'
export { default as EmployeesLoginEmployeePayslips } from '../..\\components\\EmployeesLogin\\EmployeePayslips.vue'
export { default as EmployeesLoginEmployeePersonal } from '../..\\components\\EmployeesLogin\\EmployeePersonal.vue'
export { default as EmployeesLoginEmployeeReportComponent } from '../..\\components\\EmployeesLogin\\EmployeeReportComponent.vue'
export { default as EmployeesLoginEmployeeScheduleList } from '../..\\components\\EmployeesLogin\\EmployeeScheduleList.vue'
export { default as HostCreate } from '../..\\components\\Host\\Create.vue'
export { default as HostList } from '../..\\components\\Host\\List.vue'
export { default as LeavesLeavegroups } from '../..\\components\\Leaves\\leavegroups.vue'
export { default as LeavesLeavetype } from '../..\\components\\Leaves\\leavetype.vue'
export { default as ScheduleEmployeeScheduledEmployees } from '../..\\components\\schedule_employee\\ScheduledEmployees.vue'
export { default as ScheduleEmployeeUnScheduledEmployees } from '../..\\components\\schedule_employee\\UnScheduledEmployees.vue'
export { default as SnippetsBack } from '../..\\components\\Snippets\\Back.vue'
export { default as SnippetsCamera } from '../..\\components\\Snippets\\Camera.vue'
export { default as SnippetsDatePickerCommon } from '../..\\components\\Snippets\\DatePickerCommon.vue'
export { default as SnippetsDateRangePickerCommon } from '../..\\components\\Snippets\\DateRangePickerCommon.vue'
export { default as SnippetsDaysPickerCommon } from '../..\\components\\Snippets\\DaysPickerCommon.vue'
export { default as SnippetsMonthlyFlexiHolidays } from '../..\\components\\Snippets\\MonthlyFlexiHolidays.vue'
export { default as SnippetsTimePickerCommon } from '../..\\components\\Snippets\\TimePickerCommon.vue'
export { default as SnippetsTimePickerV1 } from '../..\\components\\Snippets\\TimePickerV1.vue'
export { default as SnippetsTimePickerV2 } from '../..\\components\\Snippets\\TimePickerV2.vue'
export { default as SnippetsTimePickerV3 } from '../..\\components\\Snippets\\TimePickerV3.vue'
export { default as SnippetsTimePickerV4 } from '../..\\components\\Snippets\\TimePickerV4.vue'
export { default as SnippetsWeekendPickerCommon } from '../..\\components\\Snippets\\WeekendPickerCommon.vue'
export { default as ThemeCardDesginer } from '../..\\components\\Theme\\CardDesginer.vue'
export { default as VisitorDashboardVisitorHourChart } from '../..\\components\\Visitor\\DashboardVisitorHourChart.vue'
export { default as VisitorDashboardVisitorPieChart } from '../..\\components\\Visitor\\DashboardVisitorPieChart.vue'
export { default as VisitorListOld } from '../..\\components\\Visitor\\List_old.vue'
export { default as VisitorHistory } from '../..\\components\\Visitor\\VisitorHistory.vue'
export { default as VisitorInfo } from '../..\\components\\Visitor\\VisitorInfo.vue'
export { default as VisitorLogs } from '../..\\components\\Visitor\\VisitorLogs.vue'
export { default as VisitorLogsOld } from '../..\\components\\Visitor\\VisitorLogs_old.vue'
export { default as VisitorReport } from '../..\\components\\Visitor\\VisitorReport.vue'
export { default as VisitorRequestsList } from '../..\\components\\Visitor\\VisitorRequestsList.vue'
export { default as WidgetsAnnouncement } from '../..\\components\\widgets\\Announcement.vue'
export { default as WidgetsAttendanceLog } from '../..\\components\\widgets\\AttendanceLog.vue'
export { default as WidgetsAttendancePIE } from '../..\\components\\widgets\\AttendancePIE.vue'
export { default as WidgetsDashboardCardComponent } from '../..\\components\\widgets\\DashboardCardComponent.vue'
export { default as WidgetsDashboardComponent } from '../..\\components\\widgets\\DashboardComponent.vue'
export { default as WidgetsDepartmentMappingCreate } from '../..\\components\\widgets\\DepartmentMappingCreate.vue'
export { default as WidgetsDevice } from '../..\\components\\widgets\\Device.vue'
export { default as WidgetsDevicePIE } from '../..\\components\\widgets\\DevicePIE.vue'
export { default as WidgetsRealTimeLog } from '../..\\components\\widgets\\RealTimeLog.vue'
export { default as WidgetsReportNotification } from '../..\\components\\widgets\\ReportNotification.vue'
export { default as ZoneList } from '../..\\components\\Zone\\List.vue'
export { default as EmployeesLoginDashboardEmpDashbaordAnnouncementsV1 } from '../..\\components\\EmployeesLogin\\Dashboard\\EmpDashbaordAnnouncementsV1.vue'
export { default as EmployeesLoginDashboardEmpDashboardAttendanceChartV1 } from '../..\\components\\EmployeesLogin\\Dashboard\\EmpDashboardAttendanceChartV1.vue'
export { default as EmployeesLoginDashboardEmpDashboardLoginActivitiesV1 } from '../..\\components\\EmployeesLogin\\Dashboard\\EmpDashboardLoginActivitiesV1.vue'
export { default as EmployeesLoginDashboardEmpDashboardRealTimeLogV1 } from '../..\\components\\EmployeesLogin\\Dashboard\\EmpDashboardRealTimeLogV1.vue'
export { default as SnippetsCommonSearch } from '../..\\components\\Snippets\\Common\\Search.vue'
export { default as SnippetsCommunityCategory } from '../..\\components\\Snippets\\Community\\Category.vue'
export { default as SnippetsCommunityFloor } from '../..\\components\\Snippets\\Community\\Floor.vue'
export { default as SnippetsCommunity } from '../..\\components\\Snippets\\Community\\index.vue'
export { default as SnippetsCommunityRoom } from '../..\\components\\Snippets\\Community\\Room.vue'
export { default as SnippetsEmployeeBank } from '../..\\components\\Snippets\\Employee\\Bank.vue'
export { default as SnippetsEmployeeContact } from '../..\\components\\Snippets\\Employee\\Contact.vue'
export { default as SnippetsEmployeeCreate } from '../..\\components\\Snippets\\Employee\\Create.vue'
export { default as SnippetsEmployeeCreateEmployee } from '../..\\components\\Snippets\\Employee\\CreateEmployee.vue'
export { default as SnippetsEmployeeDocument } from '../..\\components\\Snippets\\Employee\\Document.vue'
export { default as SnippetsEmployeeEdit } from '../..\\components\\Snippets\\Employee\\Edit.vue'
export { default as SnippetsEmployeeEmirates } from '../..\\components\\Snippets\\Employee\\Emirates.vue'
export { default as SnippetsEmployeeExport } from '../..\\components\\Snippets\\Employee\\Export.vue'
export { default as SnippetsEmployeeImport } from '../..\\components\\Snippets\\Employee\\Import.vue'
export { default as SnippetsEmployeeKeyValueTable } from '../..\\components\\Snippets\\Employee\\KeyValueTable.vue'
export { default as SnippetsEmployeeLogin } from '../..\\components\\Snippets\\Employee\\Login.vue'
export { default as SnippetsEmployeeLogs } from '../..\\components\\Snippets\\Employee\\Logs.vue'
export { default as SnippetsEmployeePassport } from '../..\\components\\Snippets\\Employee\\Passport.vue'
export { default as SnippetsEmployeePayroll } from '../..\\components\\Snippets\\Employee\\Payroll.vue'
export { default as SnippetsEmployeePersonal } from '../..\\components\\Snippets\\Employee\\Personal.vue'
export { default as SnippetsEmployeeQualification } from '../..\\components\\Snippets\\Employee\\Qualification.vue'
export { default as SnippetsEmployeeSearch } from '../..\\components\\Snippets\\Employee\\Search.vue'
export { default as SnippetsEmployeeSetting } from '../..\\components\\Snippets\\Employee\\Setting.vue'
export { default as SnippetsEmployeeUpdate } from '../..\\components\\Snippets\\Employee\\Update.vue'
export { default as SnippetsEmployeeVisa } from '../..\\components\\Snippets\\Employee\\Visa.vue'
export { default as SnippetsEmployeeWorkInfo } from '../..\\components\\Snippets\\Employee\\WorkInfo.vue'
export { default as SnippetsFiltersDateRangePicker } from '../..\\components\\Snippets\\Filters\\DateRangePicker.vue'
export { default as SnippetsFiltersDropDown } from '../..\\components\\Snippets\\Filters\\DropDown.vue'
export { default as SnippetsFiltersTextField } from '../..\\components\\Snippets\\Filters\\TextField.vue'
export { default as WidgetsShiftsAutoShift } from '../..\\components\\widgets\\Shifts\\AutoShift.vue'
export { default as WidgetsShiftsFiloShift } from '../..\\components\\widgets\\Shifts\\FiloShift.vue'
export { default as WidgetsShiftsMultiInOutShift } from '../..\\components\\widgets\\Shifts\\MultiInOutShift.vue'
export { default as WidgetsShiftsOverNightShift } from '../..\\components\\widgets\\Shifts\\OverNightShift.vue'
export { default as WidgetsShiftsSingleShift } from '../..\\components\\widgets\\Shifts\\SingleShift.vue'
export { default as WidgetsShiftsSplitShift } from '../..\\components\\widgets\\Shifts\\SplitShift.vue'

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
